# Dockerfile (starter) generated by COMET
# Minimal Python container starter for astronomy / astrophysics projects
FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1     PYTHONUNBUFFERED=1     PIP_NO_CACHE_DIR=1     SETUPTOOLS_SCM_PRETEND_VERSION=0.0.0+comet

WORKDIR /app

# Install a small scientific Python baseline; extend this as needed
RUN python -m pip install --upgrade pip &&     python -m pip install numpy pandas astropy

# Copy your repository content (adjust ignore rules in .dockerignore)
COPY . .

# If your repo defines extra dependencies, install them too.
# COMET sets a pretend VCS version because Docker build contexts normally omit .git.
RUN if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi &&     if [ -f pyproject.toml ] || [ -f setup.py ] || [ -f setup.cfg ]; then python -m pip install -e .; fi

# Default command; change to your entry point/tool
CMD ["python"]